### ISSUE TITLE
Host documentation GitHub pages

### ISSUE THREAD

**Issue by matoous** [mattwparas/steel#120]
Hi!

It should be possible to host the mdbook with generated docs using [GitHub Pages](https://pages.github.com/). The full process is described here: https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#GitHub-Pages-Deploy. This could serve well for now before more elaborate approach is needed and would make it easier to explore Steel.

**Comment by mattwparas** [comment]
Great idea - I have a gh-pages hosted for tracking benchmark regressions from this repo. Do you know if its possible to host that _and_ the mdbook out of the same repo at the same time?

**Comment by mattwparas** [comment]
So I went ahead and got this set up. The docs are a bit bare bones but I will be adding to them over the next few weeks:

They can be found at https://mattwparas.github.io/steel/book/
