### ISSUE TITLE
`cargo run -- install.scm` fails with `os error 2`: no such file or directory

### ISSUE THREAD

**Issue by cgahr** [mattwparas/steel#182]
currently `nix build` and `nix shell` does not work.

Running either command errors with
```
> error: package `clap_builder v4.5.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1
> Either upgrade to rustc 1.74 or newer, or use
> cargo update -p clap_builder@4.5.2 --precise ver
> where `ver` is the latest version of `clap_builder` supporting rustc 1.72.1
```
This is easily fixable by updating  `flake.lock` (i.e. calling `nix flake update`).

After updating, `nix build` and `nix shell` now fails with a `SteelErr` with message
```
"Struct getter expected Ok, found Gc(UserDefinedStruct { fields: [Error: Io: No such file or directory (os error 2)], type_descriptor: StructTypeDescriptor(1) }), (Err Error: Io: No such file or directory (os error 2))"
```
<details>
<summary>full output</summary>
<pre>
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/ry52wmz97b9il1ixg60gk1zgmjr5pqfw-source
source root is source
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/cc HOST_CXX=/nix/store/qhpw32pz39y6i30b3vrbw5fw6zv5549f-gcc-wrapper-13.2.0/bin/c++ cargo build -j 8 --target x86_64-unknown-linux-gnu --frozen --profile release
[1m[32m   Compiling[0m autocfg v1.1.0
[1m[32m   Compiling[0m proc-macro2 v1.0.78
[1m[32m   Compiling[0m unicode-ident v1.0.12
[1m[32m   Compiling[0m libc v0.2.153
[1m[32m   Compiling[0m cfg-if v1.0.0
[1m[32m   Compiling[0m smallvec v1.13.1
[1m[32m   Compiling[0m serde v1.0.197
[1m[32m   Compiling[0m parking_lot_core v0.9.9
[1m[32m   Compiling[0m scopeguard v1.2.0
[1m[32m   Compiling[0m crossbeam-utils v0.8.19
[1m[32m   Compiling[0m version_check v0.9.4
[1m[32m   Compiling[0m log v0.4.21
[1m[32m   Compiling[0m once_cell v1.19.0
[1m[32m   Compiling[0m syn v1.0.109
[1m[32m   Compiling[0m indexmap v1.9.3
[1m[32m   Compiling[0m lock_api v0.4.11
[1m[32m   Compiling[0m num-traits v0.2.18
[1m[32m   Compiling[0m cc v1.0.90
[1m[32m   Compiling[0m signal-hook v0.3.17
[1m[32m   Compiling[0m ahash v0.8.11
[1m[32m   Compiling[0m num-bigint v0.4.4
[1m[32m   Compiling[0m quote v1.0.35
[1m[32m   Compiling[0m hashbrown v0.12.3
[1m[32m   Compiling[0m typenum v1.17.0
[1m[32m   Compiling[0m syn v2.0.52
[1m[32m   Compiling[0m core_extensions v1.5.3
[1m[32m   Compiling[0m unicode-width v0.1.11
[1m[32m   Compiling[0m rustix v0.38.31
[1m[32m   Compiling[0m bitflags v1.3.2
[1m[32m   Compiling[0m getrandom v0.2.12
[1m[32m   Compiling[0m num-integer v0.1.46
[1m[32m   Compiling[0m parking_lot v0.12.1
[1m[32m   Compiling[0m signal-hook-registry v1.4.1
[1m[32m   Compiling[0m rand_core v0.6.4
[1m[32m   Compiling[0m mio v0.8.11
[1m[32m   Compiling[0m crossbeam-channel v0.5.12
[1m[32m   Compiling[0m slab v0.4.9
[1m[32m   Compiling[0m num-rational v0.4.1
[1m[32m   Compiling[0m zerocopy v0.7.32
[1m[32m   Compiling[0m core_extensions_proc_macros v1.5.3
[1m[32m   Compiling[0m tstr_proc_macros v0.2.2
[1m[32m   Compiling[0m linux-raw-sys v0.4.13
[1m[32m   Compiling[0m paste v1.0.14
[1m[32m   Compiling[0m bitflags v2.4.2
[1m[32m   Compiling[0m serde_json v1.0.114
[1m[32m   Compiling[0m tstr v0.2.3
[1m[32m   Compiling[0m signal-hook-mio v0.2.3
[1m[32m   Compiling[0m psm v0.1.21
[1m[32m   Compiling[0m codegen v0.2.0
[1m[32m   Compiling[0m abi_stable_shared v0.11.0
[1m[32m   Compiling[0m crossbeam-epoch v0.9.18
[1m[32m   Compiling[0m typed-arena v2.0.2
[1m[32m   Compiling[0m hashbrown v0.14.3
[1m[32m   Compiling[0m thiserror v1.0.57
[1m[32m   Compiling[0m memchr v2.7.1
[1m[32m   Compiling[0m itoa v1.0.10
[1m[32m   Compiling[0m ryu v1.0.17
[1m[32m   Compiling[0m utf8parse v0.2.1
[1m[32m   Compiling[0m bitmaps v2.1.0
[1m[32m   Compiling[0m crossbeam-deque v0.8.5
[1m[32m   Compiling[0m crossterm v0.23.2
[1m[32m   Compiling[0m repr_offset v0.2.2
[1m[32m   Compiling[0m dashmap v5.5.3
[1m[32m   Compiling[0m as_derive_utils v0.11.0
[1m[32m   Compiling[0m num-iter v0.1.44
[1m[32m   Compiling[0m stacker v0.1.15
[1m[32m   Compiling[0m crossbeam-queue v0.3.11
[1m[32m   Compiling[0m im-rc v15.1.0
[1m[32m   Compiling[0m generational-arena v0.2.9
[1m[32m   Compiling[0m libloading v0.7.4
[1m[32m   Compiling[0m termcolor v1.4.1
[1m[32m   Compiling[0m byteorder v1.5.0
[1m[32m   Compiling[0m option-ext v0.2.0
[1m[32m   Compiling[0m const_panic v0.2.8
[1m[32m   Compiling[0m futures-task v0.3.30
[1m[32m   Compiling[0m pin-utils v0.1.0
[1m[32m   Compiling[0m ppv-lite86 v0.2.17
[1m[32m   Compiling[0m arrayvec v0.5.2
[1m[32m   Compiling[0m strsim v0.11.0
[1m[32m   Compiling[0m futures-core v0.3.30
[1m[32m   Compiling[0m pin-project-lite v0.2.13
[1m[32m   Compiling[0m fxhash v0.2.1
[1m[32m   Compiling[0m dirs-sys v0.4.1
[1m[32m   Compiling[0m pretty v0.12.3
[1m[32m   Compiling[0m crossbeam v0.8.4
[1m[32m   Compiling[0m rand_chacha v0.3.1
[1m[32m   Compiling[0m coolor v0.5.0
[1m[32m   Compiling[0m sized-chunks v0.6.5
[1m[32m   Compiling[0m serde_derive v1.0.197
[1m[32m   Compiling[0m thiserror-impl v1.0.57
[1m[32m   Compiling[0m futures-macro v0.3.30
[1m[32m   Compiling[0m rand_xoshiro v0.6.0
[1m[32m   Compiling[0m minimad v0.10.0
[1m[32m   Compiling[0m iana-time-zone v0.1.60
[1m[32m   Compiling[0m either v1.10.0
[1m[32m   Compiling[0m home v0.5.9
[1m[32m   Compiling[0m chrono v0.4.35
[1m[32m   Compiling[0m which v4.4.2
[1m[32m   Compiling[0m futures-util v0.3.30
[1m[32m   Compiling[0m rand v0.8.5
[1m[32m   Compiling[0m termimad v0.21.1
[1m[32m   Compiling[0m steel-derive v0.5.0 (/build/source/crates/steel-derive)
[1m[32m   Compiling[0m abi_stable_derive v0.11.3
[1m[32m   Compiling[0m dirs v5.0.1
[1m[32m   Compiling[0m codespan-reporting v0.11.1
[1m[32m   Compiling[0m aho-corasick v1.1.2
[1m[32m   Compiling[0m anstyle-parse v0.2.3
[1m[32m   Compiling[0m quickscope v0.2.0
[1m[32m   Compiling[0m futures-executor v0.3.30
[1m[32m   Compiling[0m dirs-sys-next v0.1.2
[1m[32m   Compiling[0m im-lists v0.8.0
[1m[32m   Compiling[0m nibble_vec v0.1.0
[1m[32m   Compiling[0m anstyle-query v1.0.2
[1m[32m   Compiling[0m radix_fmt v1.0.0
[1m[32m   Compiling[0m weak-table v0.3.2
[1m[32m   Compiling[0m anstyle v1.0.6
[1m[32m   Compiling[0m endian-type v0.1.2
[1m[32m   Compiling[0m regex-syntax v0.8.2
[1m[32m   Compiling[0m colorchoice v1.0.0
[1m[32m   Compiling[0m anstream v0.6.13
[1m[32m   Compiling[0m radix_trie v0.2.1
[1m[32m   Compiling[0m dirs-next v2.0.0
[1m[32m   Compiling[0m fd-lock v3.0.13
[1m[32m   Compiling[0m nix v0.25.1
[1m[32m   Compiling[0m lazy_static v1.4.0
[1m[32m   Compiling[0m clap_lex v0.7.0
[1m[32m   Compiling[0m unicode-segmentation v1.11.0
[1m[32m   Compiling[0m heck v0.4.1
[1m[32m   Compiling[0m clap_derive v4.5.0
[1m[32m   Compiling[0m regex-automata v0.4.6
[1m[32m   Compiling[0m rustyline v10.1.1
[1m[32m   Compiling[0m clap_builder v4.5.2
[1m[32m   Compiling[0m steel-gen v0.2.0 (/build/source/crates/steel-gen)
[1m[32m   Compiling[0m regex v1.10.3
[1m[32m   Compiling[0m num-complex v0.4.5
[1m[32m   Compiling[0m hashbrown v0.13.2
[1m[32m   Compiling[0m steel-core v0.6.0 (/build/source/crates/steel-core)
[1m[32m   Compiling[0m bincode v1.3.3
[1m[32m   Compiling[0m lasso v0.7.2
[1m[32m   Compiling[0m abi_stable v0.11.3
[1m[32m   Compiling[0m num v0.4.1
[1m[32m   Compiling[0m colored v2.1.0
[1m[32m   Compiling[0m steel-parser v0.6.0 (/build/source/crates/steel-parser)
[1m[32m   Compiling[0m rustyline-derive v0.7.0
[1m[32m   Compiling[0m is-terminal v0.4.12
[1m[32m   Compiling[0m humantime v2.1.0
[1m[32m   Compiling[0m clap v4.5.2
[1m[32m   Compiling[0m env_logger v0.10.2
[1m[32m   Compiling[0m async-ffi v0.5.0
[1m[32m   Compiling[0m steel-repl v0.6.0 (/build/source/crates/steel-repl)
[1m[32m   Compiling[0m steel-doc v0.6.0 (/build/source/crates/steel-doc)
[1m[32m   Compiling[0m steel-interpreter v0.6.0 (/build/source)
[1m[32m    Finished[0m release [optimized] target(s) in 3m 49s
Executing cargoInstallPostBuildHook
Finished cargoInstallPostBuildHook
Finished cargoBuildHook
buildPhase completed in 3 minutes 50 seconds
@nix { "action": "setPhase", "phase": "installPhase" }
Running phase: installPhase
Executing cargoInstallHook
/build/source/cogs /build/source
cogs directory does not exist, creating now...
Package is not currently installed.
=> Installing:  '#hash((package-name . steel/lists) (path . "/build/source/cogs/lists") (version . "0.1.0") (dependencies . ())) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/lists 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/lists

Package is not currently installed.
=> Installing:  '#hash((path . "/build/source/cogs/command-line") (version . "0.1.0") (package-name . steel/command-line) (dependencies . ())) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/command-line 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/command-line

Package is not currently installed.
=> Installing:  '#hash((package-name . steel/sorting) (version . "0.1.0") (dependencies . ()) (path . "/build/source/cogs/sorting")) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/sorting 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/sorting

Package is not currently installed.
=> Installing:  '#hash((dependencies . ()) (package-name . steel/collections) (path . "/build/source/cogs/collections") (version . "0.1.0")) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/collections 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/collections

Package is not currently installed.
=> Installing:  '#hash((package-name . steel/tests) (dependencies . ()) (version . "0.1.0") (path . "/build/source/cogs/tests")) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/tests 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/tests

Package is not currently installed.
=> Installing:  '#hash((version . "0.1.0") (path . "/build/source/cogs/srfi") (package-name . srfi) (dependencies . ())) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/srfi 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/srfi

Package is not currently installed.
=> Installing:  '#hash((dependencies . ()) (package-name . steel/fs) (version . "0.1.0") (path . "/build/source/cogs/fs")) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/fs 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/fs

Package is not currently installed.
=> Installing:  '#hash((version . "0.1.0") (package-name . steel/time) (path . "/build/source/cogs/time") (dependencies . ())) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/time 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel/time

Package is not currently installed.
=> Installing:  '#hash((path . "/build/source/cogs/installer") (dependencies . ()) (version . "0.1.0") (package-name . installer)) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/installer 
✅ Installed package to: /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/installer

Package is not currently installed.
=> Installing:  '#hash((path . "/build/source/cogs/slack") (version . "0.1.0") (dependencies . ('#hash((#:path . "../libs/steel-websockets") (#:name . steel-websockets)) '#hash((#:path . "../libs/steel-webrequests") (#:name . steel-webrequests)))) (package-name . slack/websocket)) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/slack/websocket 
=> Installing:  '#hash((version . "0.1.0") (package-name . steel-websockets) (dependencies . ()) (path . "../libs/steel-websockets") (dylibs . ('#hash((#:name . "steel-websockets") (#:workspace-root . "../..") (#:subdir . "libs/steel-websockets"))))) 
=> Copied package over to:  /nix/store/lh4y0sjnnqqmwmrzn91lbhfqim1md3ap-steel-interpreter-0.6.0/lib/cogs/steel-websockets 
Attempting to install:  '#hash((#:name . "steel-websockets") (#:workspace-root . "../..") (#:subdir . "libs/steel-websockets")) 
Running dylib build in:  ../libs/steel-websockets/../../libs/steel-websockets 
[0m[1m[38;5;9merror[E03][0m[1m: TypeMismatch[0m
   [0m[34m┌─[0m install.scm:11:1
   [0m[34m│[0m
[0m[34m11[0m [0m[34m│[0m 
   [0m[34m│[0m   [0m[31mStruct getter expected Ok, found Gc(UserDefinedStruct { fields: [Error: Io: No such file or directory (os error 2)], type_descriptor: StructTypeDescriptor(1) }), (Err Error: Io: No such file or directory (os error 2))[0m

Error: SteelErr { repr: Repr { kind: TypeMismatch, message: "Struct getter expected Ok, found Gc(UserDefinedStruct { fields: [Error: Io: No such file or directory (os error 2)], type_descriptor: StructTypeDescriptor(1) }), (Err Error: Io: No such file or directory (os error 2))", span: Some(2535..2544), stack_trace: Some(DehydratedStackTrace { stack_trace: [DehydratedCallContext { span: Some(0..0) }, DehydratedCallContext { span: Some(0..0) }, DehydratedCallContext { span: None }, DehydratedCallContext { span: Some(0..0) }, DehydratedCallContext { span: Some(2161..2172) }, DehydratedCallContext { span: Some(0..0) }, DehydratedCallContext { span: Some(1555..1563) }, DehydratedCallContext { span: Some(0..0) }, DehydratedCallContext { span: Some(2161..2172) }, DehydratedCallContext { span: Some(1555..1563) }, DehydratedCallContext { span: Some(2182..2186) }, DehydratedCallContext { span: Some(2426..2452) }] }) } }
/nix/store/v099hqvw5z87423p4hz1vfhzaqa07dii-stdenv-linux/setup: line 131: pop_var_context: head of shell_variables not a function context
</pre>
</details>

PS: the `popd` in line 41 in `flake.nix` seems to throw an error too, see the last line of the log

EDIT: I investigated this further. This is not a `nix flake` error! Instead this seems to originate from running `cargo run -- install.scm` from `contributing.scm` too! To me it looks like `steel-websockets` or `steel-regex` fails to install (depending on which machine I use)

**Comment by cgahr** [comment]
You probably missed my last edit :)
I could reproduce this issue on a non nixos too!

**Comment by mattwparas** [comment]
You're right - I did miss the edit! Can you try this:

```shell
git clone https://github.com/mattwparas/steel.git &&
cd steel &&
mkdir -p .steel/cogs && mkdir -p .steel/native && # Creates this directory too 
export STEEL_HOME="$(pwd)/.steel" &&
cargo build &&
cargo install --path crates/cargo-steel-lib &&
pushd cogs &&
cargo run -- install.scm &&
popd &&
cargo test --all
```

I had thought that I would create that additional directory automatically; but it seems like I don't!

**Comment by mattwparas** [comment]
Okay so I'm realizing there might be more that needs to be done. In order to install dylibs we'll need the dylib installer which is installed separately as a cargo extension (eventually it doesn't need to be) - that is located under `crates/cargo-steel-lib`. Can you first try to install that with `cargo install --path crates/cargo-steel-lib` and then run the installer? 

Apologies that this is all undocumented; this one slipped past me I think

**Comment by cgahr** [comment]
Don't worry, as much is expected! So far, I enjoy steel very much. Looking forward to build helix plugins with it!

I'll keep you posted.

**Comment by Borwe** [comment]
> Okay so I'm realizing there might be more that needs to be done. In order to install dylibs we'll need the dylib installer which is installed separately as a cargo extension (eventually it doesn't need to be) - that is located under `crates/cargo-steel-lib`. Can you first try to install that with `cargo install --path crates/cargo-steel-lib` and then run the installer?
> 
> Apologies that this is all undocumented; this one slipped past me I think. There could be other things that I'm missing as well but that would be the first step to try debugging this

Thanks, had similar problem, but not using nix, just plain ubuntu, this fixed it.
