### ISSUE TITLE
`register_value_with_doc` doesn't utilize the doc part

### ISSUE THREAD

**Issue by shenlebantongying** [mattwparas/steel#194]
I was looking at the doc and how the doc are generated.

It appears that various built-in functions are missing in the generated documentation (the book) and the built-in `(help indent)`, such as `cons`, `reverse`...

All these are missing, `(help cons)` doesn't print `CONS_DOC`

https://github.com/mattwparas/steel/blob/d81f428767ad8872beaf628791b7351df320b147/crates/steel-core/src/primitives/lists.rs#L92-L95

**Comment by mattwparas** [comment]
Thanks for the report. I looked into it and it's just a bit of an oversight as I changed some of the implementation with doc handling. I'll have a PR today which updates them to be included

**Comment by mattwparas** [comment]
Should also be fixed in #193 - I just tacked it in there
