### ISSUE TITLE
Running cogs/install.scm error

### ISSUE THREAD

**Issue by Mawfyy** [mattwparas/steel#216]
Hello, I like so much steel!! It's my first time to deal with.

I've been trying to run in the root of repo this command: 
`cargo run -- cogs/install.scm`

But i get this: 
![image](https://github.com/mattwparas/steel/assets/94380448/1daac419-e5fe-4423-9757-2e676143d44e)

Thank you for taking the time to review this issue. Your help is greatly appreciated!

**Comment by mattwparas** [comment]
Did you follow the instructions found [here](https://github.com/mattwparas/steel/blob/master/CONTRIBUTING.md)?

**Comment by Mawfyy** [comment]
Thank you for taking the time to respond to this issue.

Yes, i did it, without any results.

![image](https://github.com/mattwparas/steel/assets/94380448/6277fd65-a552-49e0-bc74-ca972e8dfd3b)

**Comment by mattwparas** [comment]
Got it, thanks - can you try running `install.scm` from the `cogs` directory?

**Comment by Mawfyy** [comment]
Sure, I'll try.

I did run the command again, and i get this:
![image](https://github.com/mattwparas/steel/assets/94380448/93aed46d-3af6-4e78-bf03-8bb37de90a52)

**Comment by Mawfyy** [comment]
i did re-run the command again, and i got this:
![image](https://github.com/mattwparas/steel/assets/94380448/7db24b44-bca1-4ac0-9ab7-e70b16dce1b5)

**Comment by mattwparas** [comment]
Was this from running `cargo run -- install.scm` from the `cogs` directory? Also - can you delete the contents of `$STEEL_HOME` to get a clean slate?

I was able to reproduce the initial error, so the instructions do need to be updated, however when I ran `install.scm` from the cogs directory with a clean slate, everything ran successfully.

**Comment by Mawfyy** [comment]
I ran and works!!!
```
cd cogs
cargo run -- install.scm
```

Thank you so much
