### ISSUE TITLE
When using <= in let* body, it can't deal with rational number

### ISSUE THREAD

**Issue by jkilopu** [mattwparas/steel#246]
The picture speaks for itself: 
![image](https://github.com/user-attachments/assets/37971c7f-b4d5-4023-861f-dc4389e78942)
I find this behavior a bit odd and can’t figure out why.

**Comment by mattwparas** [comment]
It's a bug, I'll have a fix shortly, looks like the <= is getting lowered to an opcode and the associated handler is missing the handling for rational numbers
