### ISSUE TITLE
Installing and using webrequests

### ISSUE THREAD

**Issue by Borwe** [mattwparas/steel#292]
I can see there is a FFImodule in /lib/steel-webrequests that should be able to provide web request capabalities, my question is though how can I use it, `cargo xtask install` didn't seem to add this module

**Comment by mattwparas** [comment]
Run `cargo steel-lib` from that directory in order to install the shared library directly, or alternatively you can do:
```
cargo run -- cogs/install.scm libs/steel-webrequests
```

I'm currently working on a package manager that will make this all easier 🙂

**Comment by Borwe** [comment]
Worked
