### ISSUE TITLE
Module system

### ISSUE THREAD

**Issue by mattwparas** [mattwparas/steel#33]
Add as special forms a way to provide and require files from a script

For example:
```scheme
;; sort.scm
(provide sort)
(define (sort lst) ...)
```

```scheme
(require "sort.scm")
(sort (list 6 3 5 4 1 2)) ;; '(1 2 3 4 5 6)
```

Only functions provided by one file should be available in a file that requires them.

**Comment by tov** [comment]
You should read this: <https://www.cs.utah.edu/plt/publications/macromod.pdf>. (I’m thrilled with what you’re doing here!)

**Comment by mattwparas** [comment]
Thanks! My first attempt at modules actually failed for some of the reasons described here (macro expansion was not playing nicely!). I'll take a look at this and hopefully it can help fix those problems
